In [ ]:
# import numpy as np
# for the 1st time there will occur error

# ModuleNotFoundError: No module named 'numpy'


In [3]:
# installation in jupyter notebook

# !pip install numpy

# (but "pip install numpy" install also works)

# in terminal
# pip install numpy

In [1]:
import numpy as np

# Creating NumPy Arrays

## np.array()

In [5]:
list1 = [1,2,3]

In [16]:
print(type(list1))

#converting list to array
array1 = np.array(list1)

print(array1)
print(type(array1))
print(array1.ndim)

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
1


In [15]:
# list lai array ma convert garda eutai datatype ma rakhne

### creating 2D array

In [18]:
list2 = [[1,2], [3,4]]
array2 = np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


# np.zeros()

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3))
# tuple banayera pass garnu parxa if multiple dimension cha vane

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# np.ones()

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# np.full()

In [21]:
np.full(5, -2)

array([-2, -2, -2, -2, -2])

In [22]:
np.full((2,3), -2)

array([[-2, -2, -2],
       [-2, -2, -2]])

In [23]:
# note: np.full(dimension, value)

# np.arrange()

In [25]:
# np.array(range(start, stop, step))
# array + range = arrange

In [28]:
np.arange(5)

# by default takes stop

array([0, 1, 2, 3, 4])

In [29]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

# np.linspace()

In [32]:
# np.linspace(start, stop, num_of_elements_in_between)

np.linspace(1, 10, 2)

array([ 1., 10.])

In [33]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [35]:
np.linspace((1, 2), (5, 10), 5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

In [36]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

# np.diag()

In [43]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [45]:
np.diag([2, 3, 4, 5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [ ]:
# shifting

In [49]:
np.diag([2, 3, 4, 5], k =1)
# adds 0 in front and lower

array([[0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0]])

In [48]:
np.diag([2, 3, 4, 5], k = -1)
# adds 0 in upper and at back

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0]])

# np.eye()

In [50]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.eye(5, k = -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [53]:
np.eye(5, k = 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [54]:
#  diff betn diag and eye is that eye will shift diagnol and doesnot adds 0 value in respextive dimension

# np.identity()

In [55]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
#  similar to np.eye() but eye() in used more in industry

# np.random()
- mostly used while training machine

In [57]:
np.random.rand(2,3)

array([[0.50367955, 0.89628901, 0.58035476],
       [0.01960744, 0.58609493, 0.13428788]])

In [59]:
np.random.rand(2,3)

array([[0.49141355, 0.06677753, 0.33909219],
       [0.4381815 , 0.93520138, 0.507508  ]])

In [9]:
# 0 and 1 ko bich ma hunxa

# np.random.rand(2,3)
# rand returns random numbers between 0 and 1

#### random.randint()

In [3]:
np.random.randint(2,3)
# gives random value between two numbers i.e. 2 and 3
# works same like range in for loop

2

In [8]:
np.random.randint(2,10)

4

In [17]:
test = np.random.rand(2,3,4)
test

array([[[0.58116742, 0.20908108, 0.31113688, 0.98909825],
        [0.25071491, 0.65553104, 0.62132654, 0.63294824],
        [0.79384597, 0.12978253, 0.6578899 , 0.70394225]],

       [[0.65338286, 0.6371845 , 0.97808766, 0.74051766],
        [0.21868143, 0.17887475, 0.14962428, 0.13651798],
        [0.18210336, 0.24557617, 0.17079699, 0.46633107]]])

In [23]:
test.shape
# 2 ta different element ko 3 ta row and 4 columns

(2, 3, 4)

In [22]:
test.ndim

3

# np.random.randint()

In [15]:
np.random.randint(2, 7, size = (3,7))

# start:2
# stop: 7
# dimension: size= (3,7)

# result: this gives array value greater than 1


array([[2, 3, 4, 2, 2, 4, 5],
       [3, 6, 4, 6, 5, 6, 4],
       [6, 2, 2, 5, 5, 5, 2]])

In [67]:
# practise

In [12]:
np.random.randint(2, (3,7))

array([2, 3])

In [62]:
np.random.rand(2,3,4,5)

array([[[[0.01606574, 0.62492069, 0.3815552 , 0.91197544, 0.07498387],
         [0.25375607, 0.68813115, 0.43993434, 0.81273413, 0.96870243],
         [0.76915324, 0.64893458, 0.00363109, 0.37099829, 0.75524281],
         [0.49228687, 0.16403938, 0.25269956, 0.33633764, 0.04808333]],

        [[0.6573269 , 0.10865388, 0.23252569, 0.51272505, 0.22888831],
         [0.73235632, 0.06423743, 0.76914539, 0.6114299 , 0.77323796],
         [0.30924232, 0.65628003, 0.05694525, 0.3269997 , 0.58600293],
         [0.73393032, 0.40015684, 0.84507164, 0.41714698, 0.37238668]],

        [[0.03299555, 0.97731078, 0.85871915, 0.86482308, 0.68016021],
         [0.80726909, 0.1147999 , 0.32464182, 0.77016194, 0.59032164],
         [0.77662827, 0.15925401, 0.88873694, 0.06850034, 0.66929389],
         [0.29700946, 0.10270062, 0.99583609, 0.27181393, 0.82169144]]],


       [[[0.32329167, 0.96095664, 0.68476283, 0.10376072, 0.1778927 ],
         [0.77384518, 0.14747238, 0.44588527, 0.75432562, 0.51560755]

In [63]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [64]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(4)

# by default 1 row with 4 column

array([0., 0., 0., 0.])

In [14]:
np.zeros((4,3))
# 4 individual row with 3 column

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])