- bool
- int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float16, float32, float64
- complex64, complex128

You can create arrays of a specific datatype using the dtype argument when you create the array


In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3], dtype=np.int32) # Create an array of integers
b = np.array([1.0, 2.0 , 3.0], dtype=np.float64)  # Create an array of floating-point numbers
c = np.array([True, False , True], dtype=np.bool_)    # Create an array of booleans

# there is diff betn bool and bool_ where it is used especially in math

print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
bool


In [6]:
d = np.array([1, 2, 3], dtype = np.float64)
d

array([1., 2., 3.])

In [4]:
e = np.array([1.0, 2.0, 3.0], dtype = np.int32)
e

array([1, 2, 3])

In [10]:
f = np.array([True, False, True], dtype = np.int32)
f

array([1, 0, 1])

In [5]:
f = np.array([True, False, True], dtype = np.int64)
f

array([1, 0, 1], dtype=int64)

In [6]:
f = np.array([True, False, True], dtype = np.float32)
f

array([1., 0., 1.], dtype=float32)

# astype()

In [11]:
a.dtype

dtype('int32')

In [12]:
g = a.astype(np.float32)

In [13]:
g

array([1., 2., 3.], dtype=float32)

In [8]:
# dtype works during assigining and astype works at converting