In [1]:
import numpy as np

# Elementwise Operations

In [3]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [9, 8, 7]])

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [4]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [9, 8, 7]])

In [5]:
a

array([[4, 5, 6],
       [5, 7, 9]])

In [6]:
b

array([[1, 2, 3],
       [9, 8, 7]])

In [7]:
a + b

array([[ 5,  7,  9],
       [14, 15, 16]])

In [8]:
a - b

array([[ 3,  3,  3],
       [-4, -1,  2]])

In [9]:
# sin cos tan: these are universal trigonometric fxn
# np.expm1(): exp(x)-1

## Matirx Operation

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
b

array([[5, 6],
       [7, 8]])

In [13]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [14]:
c = np.array([[1, 2, 3], [3, 4, 5]])
d = np.array([[5, 6], [7, 8]])

In [15]:
np.dot(c, d)

# here c matrix have order 2*3 and d have 2*2

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [16]:
np.dot(d,c)

array([[23, 34, 45],
       [31, 46, 61]])

In [18]:
a

array([[1, 2],
       [3, 4]])

In [17]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [19]:
# trace give sum of diagonal element
# helps in confusion matrix
np.trace(a)

5

In [21]:
np.linalg.det(a)

# used for determinant

-2.0000000000000004

In [22]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
# Note: we cannot find determinant and inverse other than square matrix

In [24]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [25]:
a = [[1, 2], [3, 5]]
b = [1, 2]

In [26]:
# 1x + 2y = 1
# 3x + 5y = 2

In [27]:
np.linalg.solve(a, b)

array([-1.,  1.])

## Broadcasting

In [32]:
a = np.array([[1, 2], [3, 5]])
b = np.array([10, 20])

In [33]:
a

array([[1, 2],
       [3, 5]])

In [34]:
b

array([10, 20])

In [35]:
a + b

array([[11, 22],
       [13, 25]])

In [36]:
# thorai vayeko row lai multiple times repeat garne

In [38]:
# [1, 2        [10, 20
#               10 20]
#  3, 4]   

In [ ]:
# yaha element wise operation vai rakheko cha

# Why numpy over python's for loop

In [11]:
import numpy as np
import time

# Using Numpy for element-wise multiplication
a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
c = a * b
end = time.time()
numpy_execution_time = end - start
print("Time taken by NumPy: {:.6f} seconds".format(numpy_execution_time))

# Using Python for loop for element-wise multiplication
a = list(a)
b = list(b)
c = []

start= time.time()
for i in range(len(a)):
    c.append(a[i] * b[i])
end = time.time()
for_loop_execution_time = end - start
print("Time taken by NumPy: {:.6f} seconds".format(end - start))

print(f"Numpy is {int(for_loop_execution_time/numpy_execution_time)} times faster the Python! ")


Time taken by NumPy: 0.016000 seconds
Time taken by NumPy: 0.390121 seconds
Numpy is 24 times faster the Python! 


In [12]:
# {:.6f} = holds 6 digits after decimal

# e.g:
# 0.016000 seconds