In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4], [5, 6]])
mask = np.array([True, False, True])

In [5]:
b = a[mask]
print(b)

[[1 2]
 [5 6]]


In [8]:
mask = np.array([[True, False], [True, True], [True, False]])

In [9]:
a[mask]

array([1, 3, 4, 5])

In [10]:
mask = np.array([[True, Fasle], [True], [True, False]])

NameError: name 'Fasle' is not defined

In [13]:
mask = np.array([[True, False], True, [True, False]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [14]:
mask = np.array([[True, False], False, [True, False]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [18]:
a = np.array([[1, 2], [3, 4], [5, 6]])
mask = (a > 2)

In [16]:
a[mask]

array([3, 4, 5, 6])

In [22]:
a.ndim


2

In [21]:
a.shape

(3, 2)

In [4]:
a = np.array(6)
a

array(6)

In [5]:
a.ndim

0

In [7]:
a = np.array([6])
a

array([6])

In [8]:
a.ndim

1

In [12]:
# converting array to list

In [11]:
a = list(a)
a


[6]