# 1D Array: `array_name[start:stop:step]` (Similar to Python list)

# 2D Array: `array_name[row_idx, col_idx]` (Similar to Matrix)

# ND Array: `array_name[dim1_idx, dim2_idx, ..., dimN_idx]`

In [2]:
# similar to python list

In [4]:
list1 = [1,2,3,4]

In [5]:
list1[1:3]

[2, 3]

In [9]:
import numpy as np

# One Dimensional Array

In [6]:
list1 = [1,2,3,4,5,6,7,8]

In [7]:
list1[1:7:2]

[2, 4, 6]

In [10]:
array1 = np.array(list1)

In [11]:
array1[1:7:2]

array([2, 4, 6])

# Multi Dimensional

In [9]:
list2 = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5 , 7, 9, 11 , 13, 15]]

In [13]:
list2[0][5:]

# list2[0][5:8] last item narakne indexing ma

[6, 7, 8]

In [14]:
array2 = np.array(list2)

In [15]:
array2[0][5:]

array([6, 7, 8])

In [18]:
array2[0, 5:]

array([6, 7, 8])

In [19]:
array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [20]:
# 2,3,4
# 3,5,7

In [22]:
array2[0,1:4 ]

array([2, 3, 4])

In [23]:
array2[:, 1:4]

array([[2, 3, 4],
       [3, 5, 7]])

In [30]:
array2[(0,1), [0]]

array([1, 1])

In [31]:
array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [46]:
array2[:, 1::2]

# [start:stop:step] 

array([[ 2,  4,  6,  8],
       [ 3,  7, 11, 15]])

In [49]:
list3 = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5 , 7, 9, 11 , 13, 15],[15, 25, 9999, 376, 19, 420, 786,555]]

In [51]:
array3 = np.array(list3)

In [52]:
array3

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   1,    3,    5,    7,    9,   11,   13,   15],
       [  15,   25, 9999,  376,   19,  420,  786,  555]])

In [65]:
array3[1:, 4:7]

# start:stop:step

array([[  9,  11,  13],
       [ 19, 420, 786]])

In [67]:
array3.ndim

2

In [69]:
array3.shape

(3, 8)

In [72]:
array3.shape[0]

3

In [73]:
array3

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   1,    3,    5,    7,    9,   11,   13,   15],
       [  15,   25, 9999,  376,   19,  420,  786,  555]])

In [80]:
list4 = [[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 3, 5 , 7], [9, 11 , 13, 15]],[[15, 25, 9999, 376], [19, 420, 786,555]]]



In [81]:
array4 = np.array(list4)

In [82]:
array4

array([[[   1,    2,    3,    4],
        [   5,    6,    7,    8]],

       [[   1,    3,    5,    7],
        [   9,   11,   13,   15]],

       [[  15,   25, 9999,  376],
        [  19,  420,  786,  555]]])

In [83]:
array4.ndim

3

In [84]:
array4.shape

(3, 2, 4)

In [85]:
# list ko slice list nai huna parxa
# matrix ko ....
# 1d ko slice 1d le nai garnu parxa
# 2d ko ....
# 3d ko ......

SyntaxError: invalid decimal literal (2764812581.py, line 3)