In [1]:
# numpy is a module. Module behave as a class. So, it have methods and attributes

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], [4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [4]:
a = np.array([[1,2,3], [4,5,6]])

In [5]:
a.shape

(2, 3)

In [19]:
a.dtype

dtype('int32')

In [8]:
a.ndim

2

In [10]:
a.flatten()
# eg: you will be working on
# deep learning
# convolution network

array([1, 2, 3, 4, 5, 6])

In [11]:
a.sum()

21

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a.max()

6

In [14]:
a.max(axis = 0)

array([4, 5, 6])

In [15]:
a.max(axis = 1)

array([3, 6])

In [21]:
a.dtype
# object chai 32 bit ma cha

dtype('int32')

In [23]:
a.argmax(axis = 1)
# argmax le memory change garera lida raixa

array([2, 2], dtype=int64)

In [16]:
a.shape

(2, 3)

In [24]:
# NOTE: Product of elements should be conserved
# 3 * 2 = 6 elements

a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
b = a.reshape((1,2,3))

In [29]:
b

array([[[1, 2, 3],
        [4, 5, 6]]])

In [31]:
b.shape

(1, 2, 3)

In [33]:
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])

In [34]:
# axis = 0, column


In [43]:
np.concatenate((m,n), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.concatenate((m,n))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
np.concatenate((m,n), axis = 0)
# column wala preserve gar vaneko
# column 2 cha so


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
# [1,2],[3,4] yo euta column
# [5,6],[7,8] yo arko column

# [1,2][5,6] yo arko column

In [37]:
np.concatenate((m,n), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [48]:
string = 'Hello! How are you?'
string.split()

['Hello!', 'How', 'are', 'you?']

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a = a.reshape(6)

In [42]:
a

array([1, 2, 3, 4, 5, 6])

In [46]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [47]:
# a lai 3 ta ma split gar vneko but factor of given number huna chai paryo

In [ ]:
# split according to user

In [50]:
a

array([1, 2, 3, 4, 5, 6])

In [49]:
np.split(a, [2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]